[package]
name = "crackhead"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.24.0"


[[bin]]
name = "crackhead"
path = "backend/src/main.rs"
